version: '3.8'

services:
  # PHP-FPM Service
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_php
    volumes:
      - ./src:/var/www
    networks:
      - laravel_network
    depends_on:
      - mysql

  # Nginx Service
  nginx:
    image: nginx:latest
    container_name: laravel_nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./src:/var/www
    ports:
      - "8080:80"  # Lokale Entwicklung Port, für Server ändern
    networks:
      - laravel_network
    depends_on:
      - php

  # MySQL Service
  mysql:
    image: mysql:5.7
    container_name: laravel_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - laravel_network

networks:
  laravel_network:
    driver: bridge

volumes:
  mysql_data:
    driver: local
